services:
  mysqldb:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: contact_database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    expose:
      - 3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  contact-list-service:
    image: docker.io/anthonyvks/contact-list-service-kuehne-nagel:latest
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_DATABASE: contact_database
      USERNAME: user
      PASSWORD: password
      SPRING_PROFILES_ACTIVE: mysql
    ports:
      - 8080:8080
    expose:
      - 8080
    depends_on:
      mysqldb:
        condition: service_healthy

  webapp:
    image: docker.io/anthonyvks/contact-list-angular-app-kuehne-nagel:latest
    environment:
      BASEURL: 'http\:\/\/localhost\:8080\/api'
    ports:
      - 80:80
    expose:
      - 80
    depends_on:
      - contact-list-service